server:
  port: 8086

spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  data:
    mongodb:
      authentication-database: admin
      username: Guillermo
      password: 123456g
      database: amigoscode
      port: 27017
      host: localhost
